example-app/src/main/kotlin/experimental/cms/dsl/Lib.kt
example-app/src/main/kotlin/experimental/cms/dsl/Site.kt
example-app/src/main/kotlin/experimental/cms/dsl/shell/CmsModelApplication.kt
example-app/src/main/resources/META-INF/spring/spring-shell-plugin.xml
example-app/src/main/resources/com/example/app/config/default.properties
example-app/src/main/webapp/META-INF/resources/contexts/development.properties

updated dsl to resolve placeholders for page paths
VT-374

updated default.properties with additional properties

---

example-app/.idea/dictionaries/aholt.xml
example-app/src/main/groovy/com/example/app/config/automation/StarterSiteDataConversionVersion1.groovy
example-app/src/main/java/com/example/app/profile/model/location/Location.java
example-app/src/main/java/com/example/app/profile/model/terminology/FallbackProfileTermProvider.java
example-app/src/main/java/com/example/app/profile/model/terminology/ProfileTermProvider.java
example-app/src/main/java/com/example/app/profile/model/terminology/ProfileTerms.java
example-app/src/main/java/com/example/app/profile/service/DefaultProfileTermProvider.java
example-app/src/main/java/com/example/app/profile/service/SelectedCompanyTermProvider.java
example-app/src/main/java/com/example/app/profile/ui/company/CompanyViewerComponent.java
example-app/src/main/java/com/example/app/profile/ui/package-info.java
example-app/src/main/java/com/example/app/profile/ui/terminology/ProfileTerm.java
example-app/src/main/java/com/example/app/profile/ui/terminology/ProfileTermsEditor.java
example-app/src/main/java/com/example/app/profile/ui/terminology/ProfileTermsViewer.java
example-app/src/main/java/com/example/app/profile/ui/terminology/package-info.java

added ProfileTerm UIs to CoachingEntity

added terms to ProfileTerms

---

starter-app/src/demo/java/com/example/app/config/automation/demo/DemoDataConversionVersion1.java
starter-app/src/libraries/groovy/ScriptGenerator/Frontend/StarterSiteMenuScript.groovy
starter-app/src/main/java/com/example/app/profile/ui/ApplicationFunctions.java
starter-app/src/main/java/com/example/app/profile/ui/company/CompanyUIPermissionCheck.java
starter-app/src/main/java/com/example/app/profile/ui/company/resource/CompanyResourceManagement.java
starter-app/src/main/java/com/example/app/profile/ui/company/resource/CompanyResourcePermissionCheck.java
starter-app/src/main/java/com/example/app/profile/ui/company/resource/CompanyResourcePropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/company/resource/CompanyResourcePropertyViewer.java
starter-app/src/main/java/com/example/app/profile/ui/resource/AbstractProfileResourcePropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/resource/AbstractProfileResourcePropertyViewer.java
starter-app/src/main/java/com/example/app/profile/ui/user/MyAccountPermissionCheck.java
starter-app/src/main/java/com/example/app/profile/ui/user/UserManagementPermissionCheck.java
starter-app/src/main/java/com/example/app/support/service/ApplicationFunctionPermissionCheck.java
starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicDSL.kt
starter-app/src/main/kotlin/experimental/cms/dsl/shell/CmsModelApplication.kt
webdev/gulp-tasks/artifact/publish.js
webdev/web/src/stylesheets/default/components/_starter-menu.scss
webdev/web/src/stylesheets/default/config/_base-import.scss

got dsl working with web resources

---

starter-app/src/main/groovy/com/example/app/config/automation/note/NoteDataConversion1.groovy
starter-app/src/main/groovy/com/example/app/config/automation/profile/ProfileDataConversionVersion1.groovy
starter-app/src/main/java/com/example/app/profile/model/client/Client.java
starter-app/src/main/java/com/example/app/profile/model/company/Company.java
starter-app/src/main/java/com/example/app/profile/service/MembershipOperationConfiguration.java
starter-app/src/main/java/com/example/app/profile/service/MembershipOperationProvider.java

added company property to client
VT-388

fixed data conversion files

---

starter-app/src/main/java/com/example/app/login/oneall/service/OneAllLoginService.java

fixed checkstyle by telling it to ignore the errors

---

starter-app/src/main/java/com/example/app/login/oneall/service/OneAllLoginService.java

fixed findbugs by telling it to ignore the errors

---

starter-app/src/main/java/com/example/app/login/oneall/service/OneAllLoginService.java

fixed findbugs by telling it to ignore the errors...again

---

starter-app/src/libraries/groovy/ScriptGenerator/Frontend/AppFunctionMenuScript.groovy
starter-app/src/main/java/com/example/app/profile/model/location/LocationDAO.java
starter-app/src/main/java/com/example/app/profile/service/MembershipOperationConfiguration.java
starter-app/src/main/java/com/example/app/profile/service/MembershipOperationProvider.java
starter-app/src/main/java/com/example/app/profile/ui/ApplicationFunctions.java
starter-app/src/main/java/com/example/app/profile/ui/URLConfigurations.java
starter-app/src/main/java/com/example/app/profile/ui/URLProperties.java
starter-app/src/main/java/com/example/app/profile/ui/company/location/CompanyLocationManagement.java
starter-app/src/main/java/com/example/app/profile/ui/company/location/CompanyLocationPropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/company/location/CompanyLocationPropertyViewer.java
starter-app/src/main/java/com/example/app/profile/ui/company/location/CompanyLocationUIPermissionCheck.java
starter-app/src/main/java/com/example/app/profile/ui/company/location/package-info.java
starter-app/src/main/java/com/example/app/profile/ui/location/AbstractLocationManagement.java
starter-app/src/main/java/com/example/app/profile/ui/location/AbstractLocationPropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/location/AbstractLocationPropertyViewer.java
starter-app/src/main/java/com/example/app/profile/ui/location/LocationValueEditor.java
starter-app/src/main/java/com/example/app/profile/ui/location/LocationValueViewer.java
starter-app/src/main/java/com/example/app/profile/ui/location/package-info.java
starter-app/src/main/java/com/example/app/support/service/AppUtil.java
starter-app/src/main/java/com/example/app/support/service/Functions.java
starter-app/src/main/java/com/example/app/support/ui/contact/EmailAddressValueEditor.java
starter-app/src/main/java/com/example/app/support/ui/search/ToggleDeleteNavigationColumn.java
starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicLocationsDSL.kt
starter-app/src/main/resources/web/docroot/vtcrop/vt-img-cropper.js

Location Management UIs

---

starter-app/src/main/java/com/example/app/login/oneall/service/OneAllLoginService.java

to allow loading private key from environment variable

updated OneAllLoginService

---

starter-app/src/main/java/com/example/app/login/oneall/service/OneAllLoginService.java

autowired the wrong Environment

fixed Environment autowire

---

starter-app/src/main/java/com/example/app/login/oneall/service/OneAllLoginService.java
starter-app/src/main/kotlin/experimental/cms/dsl/shell/CmsModelApplication.kt

updated message within OneAllLoginService

fixed issue with role creation

---

webdev/gulp-tasks/artifact/publish.js
webdev/gulp-tasks/slack-send.js
webdev/package.json

added support for slack messages upon publish for webdev

---

starter-app/src/main/java/com/example/app/profile/ui/client/ClientManagement.java
starter-app/src/main/java/com/example/app/profile/ui/company/resource/CompanyResourceManagement.java
starter-app/src/main/java/com/example/app/profile/ui/user/UserManagement.java
starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicDSL.kt

added header text to management UIs

---

starter-app/.idea/dictionaries/aholt.xml
starter-app/buildSrc/src/main/groovy/com/proteusframework/build/ArtifactoryDownloader.groovy
starter-app/buildSrc/src/main/groovy/com/proteusframework/build/CreateProjectUI.groovy
starter-app/buildSrc/src/main/groovy/com/proteusframework/build/ProjectModel.groovy
starter-app/src/main/java/com/example/app/login/social/ui/SocialLoginGenerator.java
starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicOneAllDSL.kt

added option to CreateProject for database

---

starter-app/buildSrc/src/main/groovy/com/proteusframework/build/ArtifactoryDownloader.groovy

updated ArtifactoryDownloader to be less picky about urls

---

starter-app/src/main/java/com/example/app/profile/ui/location/LocationValueEditor.java
starter-app/src/main/java/com/example/app/profile/ui/location/LocationValueViewer.java
webdev/gulp-tasks/config.js
webdev/gulpfile.js
webdev/web/src/config/templates/LocationValueViewer.xml

added example templatecontainer template to webdev
updated webdev to process template containers in gulp
PF-1591

updated LocationValueViewer to be TemplateContainer

---

starter-app/src/main/java/com/example/app/profile/ui/client/ClientManagement.java
starter-app/src/main/java/com/example/app/profile/ui/client/ClientPropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/client/ClientViewerComponent.java
starter-app/src/main/java/com/example/app/profile/ui/company/AbstractCompanyPropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/company/CompanyManagement.java
starter-app/src/main/java/com/example/app/profile/ui/company/CompanyViewerComponent.java
starter-app/src/main/java/com/example/app/profile/ui/company/resource/CompanyResourceManagement.java
starter-app/src/main/java/com/example/app/profile/ui/location/AbstractLocationManagement.java
starter-app/src/main/java/com/example/app/profile/ui/location/AbstractLocationPropertyEditor.java
starter-app/src/main/java/com/example/app/profile/ui/user/UserManagement.java

added classnames to page headers
PF-1593

removed wrapping containers from page headers

---

starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicClientsDSL.kt
starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicErrorPagesDSL.kt
starter-app/src/main/kotlin/experimental/cms/dsl/Page.kt
starter-app/src/main/kotlin/experimental/cms/dsl/Site.kt
starter-app/src/main/kotlin/experimental/cms/dsl/shell/CmsModelApplication.kt

added support for error pages within DSL

---

starter-app/src/main/kotlin/com/example/app/config/automation/site/profile/basic/ProfileBasicDSL.kt

added css to password reset page in dsl

---

starter-app/src/libraries/groovy/ScriptGenerator/Frontend/AppFunctionMenuScript.groovy

updated AppFunctionMenuScript
